# Generated by Django 5.1.7 on 2025-04-03 08:26

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto_perfil',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.storage.MinioStorage(), upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=core.storage.MinioStorage(), upload_to='fotos_perfil/'),
        ),
    ]
