# Generated by Django 5.1.7 on 2025-04-10 12:21

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usuario_foto_perfil_alter_empresa_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Feira')),
                ('local', models.CharField(max_length=255, verbose_name='Local/Centro de Exposições')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='UF')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website da Feira')),
                ('contato_organizacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato da Organização')),
                ('email_organizacao', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email da Organização')),
                ('telefone_organizacao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone da Organização')),
                ('manual', models.FileField(storage=core.storage.MinioStorage(), upload_to='manuais_feira/', verbose_name='Manual da Feira')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('manual_processado', models.BooleanField(default=False, verbose_name='Manual Processado')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Feira',
                'verbose_name_plural': 'Feiras',
                'db_table': 'feiras',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='FeiraManualChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto do Chunk')),
                ('posicao', models.IntegerField(verbose_name='Posição no Documento')),
                ('pagina', models.IntegerField(blank=True, null=True, verbose_name='Número da Página')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='Embedding Vetorial')),
                ('feira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks_manual', to='core.feira')),
            ],
            options={
                'verbose_name': 'Chunk de Manual de Feira',
                'verbose_name_plural': 'Chunks de Manuais de Feira',
                'db_table': 'feira_manual_chunks',
            },
        ),
    ]
