# Generated by Django 5.1.7 on 2025-04-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feira_feiramanualchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroIndexacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Parâmetro')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('int', 'Inteiro'), ('float', 'Decimal'), ('str', 'Texto'), ('bool', 'Booleano')], default='str', max_length=20, verbose_name='Tipo de Valor')),
                ('categoria', models.CharField(choices=[('chunk', 'Chunking'), ('embedding', 'Embeddings'), ('pinecone', 'Pinecone'), ('search', 'Busca')], default='chunk', max_length=50, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Parâmetro de Indexação',
                'verbose_name_plural': 'Parâmetros de Indexação',
                'db_table': 'parametros_indexacao',
            },
        ),
        migrations.RemoveField(
            model_name='feiramanualchunk',
            name='embedding',
        ),
        migrations.AddField(
            model_name='feira',
            name='mensagem_erro',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro'),
        ),
        migrations.AddField(
            model_name='feira',
            name='pinecone_namespace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Namespace no Pinecone'),
        ),
        migrations.AddField(
            model_name='feira',
            name='processamento_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status de Processamento'),
        ),
        migrations.AddField(
            model_name='feira',
            name='progresso_processamento',
            field=models.IntegerField(default=0, verbose_name='Progresso (%)'),
        ),
        migrations.AddField(
            model_name='feira',
            name='total_chunks',
            field=models.IntegerField(default=0, verbose_name='Total de Chunks'),
        ),
        migrations.AddField(
            model_name='feira',
            name='total_paginas',
            field=models.IntegerField(default=0, verbose_name='Total de Páginas'),
        ),
        migrations.AddField(
            model_name='feiramanualchunk',
            name='pinecone_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID no Pinecone'),
        ),
    ]
