# Generated by Django 5.1.7 on 2025-04-13 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parametroindexacao_remove_feiramanualchunk_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametroindexacao',
            name='categoria',
            field=models.CharField(choices=[('chunk', 'Chunking'), ('embedding', 'Embeddings'), ('pinecone', 'Pinecone'), ('search', 'Busca'), ('qa', 'Perguntas e Respostas')], default='chunk', max_length=50, verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='FeiraManualQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pergunta Principal')),
                ('answer', models.TextField(verbose_name='Resposta')),
                ('context', models.TextField(help_text='Trecho do manual de onde a resposta foi extraída', verbose_name='Contexto Original')),
                ('similar_questions', models.JSONField(blank=True, default=list, verbose_name='Perguntas Similares')),
                ('chunk_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Chunk de Origem')),
                ('embedding_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Embedding')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Pontuação de Relevância')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_pairs', to='core.feira')),
            ],
            options={
                'verbose_name': 'Par Pergunta-Resposta',
                'verbose_name_plural': 'Pares Pergunta-Resposta',
                'db_table': 'feira_manual_qa',
                'ordering': ['-created_at'],
            },
        ),
    ]
