# Generated by Django 5.1.7 on 2025-04-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_parametroindexacao_categoria_feiramanualqa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Agente')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('llm_provider', models.CharField(help_text='Provedor do modelo de linguagem (ex: OpenAI, Anthropic)', max_length=50, verbose_name='Provedor LLM')),
                ('llm_model', models.CharField(help_text='Nome do modelo específico a ser usado', max_length=100, verbose_name='Modelo LLM')),
                ('llm_temperature', models.FloatField(default=0.7, help_text='Temperatura para geração de texto (0.0 - 1.0)', verbose_name='Temperatura')),
                ('llm_system_prompt', models.TextField(help_text='Prompt base que define o comportamento do agente', verbose_name='Prompt do Sistema')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'db_table': 'agentes',
            },
        ),
        migrations.AlterModelOptions(
            name='parametroindexacao',
            options={'verbose_name': 'Parâmetro do Banco Vetorial', 'verbose_name_plural': 'Parâmetros do Banco Vetorial'},
        ),
        migrations.AlterField(
            model_name='parametroindexacao',
            name='categoria',
            field=models.CharField(choices=[('chunk', 'Chunking'), ('embedding', 'Embedding'), ('connection', 'Connection'), ('search', 'Search'), ('qa', 'Q&A')], default='chunk', max_length=50, verbose_name='Categoria'),
        ),
    ]
