# Generated by Django 5.1.7 on 2025-04-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agente_alter_parametroindexacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='task_instructions',
            field=models.TextField(blank=True, help_text='Instruções específicas para execução de tarefas pelo agente', null=True, verbose_name='Instruções de Tarefa'),
        ),
    ]
