# Generated by Django 5.1.7 on 2025-04-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_agente_task_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='feira',
            name='chunks_namespace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feira',
            name='qa_namespace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
