# Generated by Django 5.1.7 on 2025-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_feira_chunks_namespace_feira_qa_namespace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feira',
            old_name='total_chunks',
            new_name='chunks_total',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='chunks_namespace',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='manual_processado',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='pinecone_namespace',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='processamento_status',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='progresso_processamento',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='qa_namespace',
        ),
        migrations.AddField(
            model_name='feira',
            name='chunks_processados',
            field=models.BooleanField(default=False, verbose_name='Chunks Processados'),
        ),
        migrations.AddField(
            model_name='feira',
            name='chunks_processamento_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status de Processamento de Chunks'),
        ),
        migrations.AddField(
            model_name='feira',
            name='chunks_progresso',
            field=models.IntegerField(default=0, verbose_name='Progresso de Chunks (%)'),
        ),
        migrations.AddField(
            model_name='feira',
            name='namespace_base',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Namespace Base no Pinecone'),
        ),
        migrations.AddField(
            model_name='feira',
            name='qa_processado',
            field=models.BooleanField(default=False, verbose_name='Q&A Processado'),
        ),
        migrations.AddField(
            model_name='feira',
            name='qa_processamento_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status de Processamento de Q&A'),
        ),
        migrations.AddField(
            model_name='feira',
            name='qa_progresso',
            field=models.IntegerField(default=0, verbose_name='Progresso de Q&A (%)'),
        ),
        migrations.AddField(
            model_name='feira',
            name='qa_total',
            field=models.IntegerField(default=0, verbose_name='Total de Q&A'),
        ),
    ]
