# Generated by Django 5.1.7 on 2025-04-20 15:05

import core.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_total_chunks_feira_chunks_total_and_more'),
        ('projetos', '0009_delete_conversa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_cliente', models.BooleanField(default=False, help_text='Indica se a mensagem foi enviada pelo cliente', verbose_name='É Cliente')),
                ('lida', models.BooleanField(default=False, help_text='Indica se a mensagem foi lida pelo destinatário', verbose_name='Mensagem Lida')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('importante', models.BooleanField(default=False, help_text='Marca a mensagem como importante', verbose_name='Importante')),
                ('arquivada', models.BooleanField(default=False, help_text='Indica se a mensagem foi arquivada', verbose_name='Arquivada')),
                ('tem_anexo', models.BooleanField(default=False, help_text='Indica se a mensagem possui arquivos anexados', verbose_name='Tem Anexo')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='projetos.projeto')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'db_table': 'mensagens',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='AnexoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('arquivo', models.FileField(storage=core.storage.MinioStorage(), upload_to='mensagens/anexos/', verbose_name='Arquivo')),
                ('tipo', models.CharField(help_text='Categoria do arquivo (imagem, documento, etc.)', max_length=50, verbose_name='Tipo de Arquivo')),
                ('tamanho', models.PositiveIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.mensagem')),
            ],
            options={
                'verbose_name': 'Anexo de Mensagem',
                'verbose_name_plural': 'Anexos de Mensagens',
                'db_table': 'anexos_mensagens',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('tipo', models.CharField(choices=[('mensagem', 'Nova Mensagem'), ('projeto', 'Atualização de Projeto'), ('briefing', 'Atualização de Briefing'), ('arquivo', 'Novo Arquivo'), ('sistema', 'Notificação do Sistema')], default='sistema', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('objeto_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notificacoes',
                'ordering': ['-data'],
            },
        ),
    ]
