# Generated by Django 5.1.7 on 2025-04-21 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_mensagem_options_remove_anexomensagem_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='remetente',
        ),
        migrations.DeleteModel(
            name='AnexoMensagem',
        ),
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
