# Generated by Django 5.1.7 on 2025-05-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_mensagem_destinatario_remove_mensagem_projeto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feira',
            name='contato_organizacao',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='email_organizacao',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='telefone_organizacao',
        ),
        migrations.AddField(
            model_name='feira',
            name='altura_estande',
            field=models.TextField(blank=True, null=True, verbose_name='Altura Estande'),
        ),
        migrations.AddField(
            model_name='feira',
            name='credenciamento',
            field=models.TextField(blank=True, null=True, verbose_name='Datas Credenciamento'),
        ),
        migrations.AddField(
            model_name='feira',
            name='data_horario',
            field=models.TextField(default='A definir', help_text='Ex: Dia 06 a 08/04 – das 10h00 às 20h00', verbose_name='Data e Horário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feira',
            name='eventos_simultaneos',
            field=models.TextField(blank=True, null=True, verbose_name='Eventos Simultâneos'),
        ),
        migrations.AddField(
            model_name='feira',
            name='iluminacao',
            field=models.TextField(blank=True, null=True, verbose_name='Regras para Iluminação'),
        ),
        migrations.AddField(
            model_name='feira',
            name='materiais',
            field=models.TextField(blank=True, null=True, verbose_name='Materiais Permitidos/Proibidos'),
        ),
        migrations.AddField(
            model_name='feira',
            name='mezanino',
            field=models.TextField(blank=True, null=True, verbose_name='Regras para Mezanino'),
        ),
        migrations.AddField(
            model_name='feira',
            name='outros',
            field=models.TextField(blank=True, null=True, verbose_name='Outras Regras'),
        ),
        migrations.AddField(
            model_name='feira',
            name='palcos',
            field=models.TextField(blank=True, null=True, verbose_name='Regras para Palcos'),
        ),
        migrations.AddField(
            model_name='feira',
            name='periodo_desmontagem',
            field=models.TextField(blank=True, null=True, verbose_name='Período Desmontagem'),
        ),
        migrations.AddField(
            model_name='feira',
            name='periodo_montagem',
            field=models.TextField(blank=True, null=True, verbose_name='Período Montagem'),
        ),
        migrations.AddField(
            model_name='feira',
            name='piso_elevado',
            field=models.TextField(blank=True, null=True, verbose_name='Regras para Piso Elevado'),
        ),
        migrations.AddField(
            model_name='feira',
            name='portao_acesso',
            field=models.TextField(blank=True, null=True, verbose_name='Portão de Acesso'),
        ),
        migrations.AddField(
            model_name='feira',
            name='promotora',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Promotora/Organizadora'),
        ),
        migrations.AddField(
            model_name='feira',
            name='publico_alvo',
            field=models.TextField(blank=True, null=True, verbose_name='Público-alvo'),
        ),
        migrations.AlterField(
            model_name='feira',
            name='local',
            field=models.TextField(verbose_name='Local/Endereço Completo'),
        ),
    ]
