# Generated by Django 5.1.7 on 2025-05-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_feira_contato_organizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feira',
            name='altura_estande',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Altura Estande'),
        ),
        migrations.AlterField(
            model_name='feira',
            name='eventos_simultaneos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Eventos Simultâneos'),
        ),
        migrations.AlterField(
            model_name='feira',
            name='portao_acesso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Portão de Acesso'),
        ),
        migrations.AlterField(
            model_name='feira',
            name='publico_alvo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Público-alvo'),
        ),
    ]
