# Generated by Django 5.1.7 on 2025-05-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_feira_altura_estande_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('nome', 'Nome da Feira'), ('local', 'Local/Endereço Completo'), ('data_horario', 'Data e Horário'), ('publico_alvo', 'Público-alvo'), ('eventos_simultaneos', 'Eventos Simultâneos'), ('promotora', 'Promotora/Organizadora'), ('periodo_montagem', 'Período Montagem'), ('portao_acesso', 'Portão de Acesso'), ('periodo_desmontagem', 'Período Desmontagem'), ('altura_estande', 'Altura Estande'), ('palcos', 'Regras para Palcos'), ('piso_elevado', 'Regras para Piso Elevado'), ('mezanino', 'Regras para Mezanino'), ('iluminacao', 'Regras para Iluminação'), ('outros', 'Outras Regras'), ('materiais', 'Materiais Permitidos/Proibidos'), ('credenciamento', 'Datas Credenciamento')], max_length=100, verbose_name='Campo de Cadastro')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('prioridade', models.IntegerField(default=1, help_text='Maior valor = maior prioridade', verbose_name='Prioridade')),
            ],
            options={
                'verbose_name': 'Pergunta para Campo',
                'verbose_name_plural': 'Perguntas para Campos',
                'db_table': 'campo_perguntas',
                'ordering': ['campo', '-prioridade'],
            },
        ),
        migrations.AddField(
            model_name='feiramanualqa',
            name='campo_relacionado',
            field=models.CharField(blank=True, help_text='Nome do campo do cadastro ao qual esta pergunta está relacionada', max_length=100, null=True, verbose_name='Campo Relacionado'),
        ),
        migrations.AddField(
            model_name='feiramanualqa',
            name='confianca_extracao',
            field=models.FloatField(default=0.0, help_text='Nível de confiança para extração automática (0.0 a 1.0)', verbose_name='Confiança da Extração'),
        ),
    ]
