# Generated by Django 5.1.7 on 2025-05-06 11:32

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_campopergunta_feiramanualqa_campo_relacionado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feira',
            name='materiais',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='outros',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='ultima_atualizacao',
        ),
        migrations.AddField(
            model_name='feira',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feira',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feira',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='feira',
            name='documentos',
            field=models.TextField(blank=True, null=True, verbose_name='Documentos'),
        ),
        migrations.AddField(
            model_name='feira',
            name='estrutura_aerea',
            field=models.TextField(blank=True, null=True, verbose_name='Estrutura Aérea'),
        ),
        migrations.AddField(
            model_name='feira',
            name='materiais_permitidos_proibidos',
            field=models.TextField(blank=True, null=True, verbose_name='Materiais Permitidos e Proibidos'),
        ),
        migrations.AddField(
            model_name='feira',
            name='paredes_vidro',
            field=models.TextField(blank=True, null=True, verbose_name='Paredes de Vidro'),
        ),
        migrations.AddField(
            model_name='feira',
            name='qa_mensagem_erro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feira',
            name='visibilidade_obrigatoria',
            field=models.TextField(blank=True, null=True, verbose_name='Visibilidade Obrigatória'),
        ),
        migrations.AlterField(
            model_name='campopergunta',
            name='campo',
            field=models.CharField(choices=[('nome', 'Nome da Feira'), ('descricao', 'Descrição do Evento'), ('website', 'Site da Feira'), ('local', 'Local/Endereço Completo'), ('data_horario', 'Data e Horário'), ('publico_alvo', 'Público-alvo'), ('eventos_simultaneos', 'Eventos Simultâneos'), ('promotora', 'Promotora/Organizadora'), ('periodo_montagem', 'Período Montagem'), ('portao_acesso', 'Portão de Acesso'), ('periodo_desmontagem', 'Período Desmontagem'), ('altura_estande', 'Altura Estande'), ('palcos', 'Regras para Palcos'), ('piso_elevado', 'Regras para Piso Elevado'), ('mezanino', 'Regras para Mezanino'), ('iluminacao', 'Regras para Iluminação'), ('materiais_permitidos_proibidos', 'Materiais Permitidos/Proibidos'), ('visibilidade_obrigatoria', 'Visibilidade Obrigatória'), ('paredes_vidro', 'Paredes de Vidro'), ('estrutura_aerea', 'Estrutura Aérea'), ('documentos', 'Documentos para Credenciamento'), ('credenciamento', 'Datas Credenciamento')], max_length=100, verbose_name='Campo de Cadastro'),
        ),
        migrations.AlterField(
            model_name='feira',
            name='altura_estande',
            field=models.TextField(blank=True, null=True, verbose_name='Altura Estande'),
        ),
        migrations.AlterField(
            model_name='feira',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feira',
            name='chunks_processados',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feira',
            name='chunks_processamento_status',
            field=models.CharField(default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='feira',
            name='chunks_progresso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feira',
            name='chunks_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feira',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feira',
            name='credenciamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feira',
            name='data_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='feira',
            name='data_horario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feira',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='feira',
            name='estado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='feira',
            name='eventos_simultaneos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Eventos Simultâneos'),
        ),
        migrations.AlterField(
            model_name='feira',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feira',
            name='iluminacao',
            field=models.TextField(blank=True, null=True, verbose_name='Iluminação'),
        ),
        migrations.AlterField(
            model_name='feira',
            name='local',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feira',
            name='manual',
            field=models.FileField(blank=True, null=True, upload_to=core.models.Feira.manual_upload_path),
        ),
        migrations.AlterField(
            model_name='feira',
            name='mensagem_erro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feira',
            name='mezanino',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feira',
            name='namespace_base',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feira',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feira',
            name='palcos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feira',
            name='piso_elevado',
            field=models.TextField(blank=True, null=True, verbose_name='Piso Elevado'),
        ),
        migrations.AlterField(
            model_name='feira',
            name='portao_acesso',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Portão de Acesso'),
        ),
        migrations.AlterField(
            model_name='feira',
            name='promotora',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feira',
            name='publico_alvo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Público-alvo'),
        ),
        migrations.AlterField(
            model_name='feira',
            name='qa_processado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feira',
            name='qa_processamento_status',
            field=models.CharField(default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='feira',
            name='qa_progresso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feira',
            name='qa_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feira',
            name='total_paginas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feira',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
