# Generated by Django 5.1.7 on 2025-06-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_feira_materiais_remove_feira_outros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da empresa que pode ser editada por projeto', null=True, verbose_name='Descrição da Empresa'),
        ),
    ]
