# Generated by Django 5.1.7 on 2025-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_empresa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro/Não Informar')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
