# Generated by Django 5.1.7 on 2025-11-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_crewtask_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='feira',
            name='data_extracao_regras',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Extração das Regras'),
        ),
        migrations.AddField(
            model_name='feira',
            name='regras_extraidas',
            field=models.BooleanField(default=False, help_text='Indica se as regras já foram processadas e estruturadas', verbose_name='Regras Extraídas'),
        ),
        migrations.AddField(
            model_name='feira',
            name='regras_planta_baixa',
            field=models.JSONField(blank=True, default=dict, help_text='Dados extraídos do manual para validação automática de plantas', verbose_name='Regras Estruturadas para Planta Baixa'),
        ),
    ]
