# Generated by Django 5.1.7 on 2025-03-31 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefing',
            name='projeto',
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='data_criacao',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='prazo',
            new_name='data_inicio',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='titulo',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='data_modificacao',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='gestor',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='projetista',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='valor_estimado',
        ),
        migrations.AddField(
            model_name='projeto',
            name='orcamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='projeto',
            name='prazo_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='progresso',
            field=models.IntegerField(default=0, help_text='Progresso em porcentagem (0-100)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='requisitos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AlterModelTable(
            name='projeto',
            table='projetos',
        ),
        migrations.CreateModel(
            name='ArquivoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='referencias/')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Arquivo de Referência',
                'verbose_name_plural': 'Arquivos de Referência',
                'db_table': 'arquivos_referencia',
            },
        ),
        migrations.DeleteModel(
            name='ArquivoProjeto',
        ),
        migrations.DeleteModel(
            name='Briefing',
        ),
    ]
