# Generated by Django 5.1.7 on 2025-04-02 09:20

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_remove_briefing_projeto_alter_projeto_options_and_more'),
    ]

    operations = [
    ]