# Generated by Django 5.1.7 on 2025-04-02 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_auto_20250402_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='briefing_status',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='nao_iniciado', max_length=20),
        ),
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_validacao', 'Em Validação'), ('validado', 'Validado'), ('enviado', 'Enviado'), ('revisao', 'Em Revisão'), ('aprovado', 'Aprovado')], default='rascunho', max_length=20)),
                ('etapa_atual', models.PositiveSmallIntegerField(default=1)),
                ('progresso', models.PositiveSmallIntegerField(default=0)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao_detalhada', models.TextField(blank=True, null=True)),
                ('objetivos', models.TextField(blank=True, null=True)),
                ('dimensoes', models.PositiveIntegerField(blank=True, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('paleta_cores', models.CharField(blank=True, max_length=200, null=True)),
                ('materiais_preferidos', models.TextField(blank=True, null=True)),
                ('acabamentos', models.TextField(blank=True, null=True)),
                ('iluminacao', models.TextField(blank=True, null=True)),
                ('eletrica', models.TextField(blank=True, null=True)),
                ('mobiliario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validado_por_ia', models.BooleanField(default=False)),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='briefing', to='projetos.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='BriefingArquivoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='briefing/referencias/')),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('planta', 'Planta'), ('documento', 'Documento'), ('outro', 'Outro')], max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='projetos.briefing')),
            ],
        ),
        migrations.CreateModel(
            name='BriefingConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('origem', models.CharField(choices=[('cliente', 'Cliente'), ('ia', 'IA')], max_length=10)),
                ('etapa', models.PositiveSmallIntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='projetos.briefing')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BriefingValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('atencao', 'Atenção'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], max_length=20)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacoes', to='projetos.briefing')),
            ],
            options={
                'unique_together': {('briefing', 'secao')},
            },
        ),
    ]
