# Generated by Django 5.1.7 on 2025-04-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_projeto_briefing_status_briefing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tem_briefing',
            field=models.BooleanField(default=False),
        ),
    ]
