# Generated by Django 5.1.7 on 2025-04-16 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_agente_task_instructions'),
        ('projetos', '0007_alter_briefingconversation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefing',
            name='acabamentos',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='altura_piso_outro',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='ativacao_descricao',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='categoria_projeto',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='copa_requisitos',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='deposito_requisitos',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='descricao_detalhada',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='dimensoes',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='eletrica',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='iluminacao',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='lounge_descricao',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='materiais_preferidos',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='mobiliario',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='objetivos',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='paleta_cores',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='quantidade_mesas_atendimento',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='sala_reuniao_requisitos',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='tem_ativacao',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='testeira',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='venda_no_estande',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='vitrine_descricao',
        ),
        migrations.AddField(
            model_name='briefing',
            name='area_aberta_tamanho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metragem Área Aberta (m²)'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='area_estande',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área do Estande (m²)'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='campanha_dados',
            field=models.TextField(blank=True, help_text='Informações sobre a campanha atual e como deve ser aplicada no estande', null=True, verbose_name='Campanha - Dados'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='copa_equipamentos',
            field=models.TextField(blank=True, help_text='Pia, geladeira, bancada, prateleiras, etc.', null=True, verbose_name='Equipamentos da Copa'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='copa_tamanho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metragem Copa (m²)'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='cores',
            field=models.TextField(blank=True, help_text='Cores principais, referências Pantone, amadeirado, etc.', null=True, verbose_name='Cores'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='data_desmontagem_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Término da Desmontagem'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='data_desmontagem_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início da Desmontagem'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='data_feira_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Término da Feira'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='data_feira_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Início da Feira'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='data_montagem_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Término da Montagem'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='data_montagem_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início da Montagem'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='deposito_equipamentos',
            field=models.TextField(blank=True, help_text='Prateleiras, etc.', null=True, verbose_name='Equipamentos do Depósito'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='deposito_tamanho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metragem Depósito (m²)'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='endereco_estande',
            field=models.TextField(blank=True, help_text='Localização do estande dentro do pavilhão', null=True, verbose_name='Endereço do Estande'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='feira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefings', to='core.feira', verbose_name='Feira/Evento'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='havera_ativacao',
            field=models.BooleanField(default=False, verbose_name='Haverá ativação no estande?'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='havera_venda',
            field=models.BooleanField(default=False, verbose_name='Haverá venda no estande?'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='horario_feira',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário da Feira'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='local_evento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local do Evento'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='logotipo',
            field=models.TextField(blank=True, help_text='Descreva detalhes sobre a aplicação do logotipo no estande', null=True, verbose_name='Informações sobre o Logotipo'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='material',
            field=models.TextField(blank=True, help_text='Materiais predominantes a serem utilizados', null=True, verbose_name='Materiais'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='nome_projeto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Projeto'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='objetivo',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivo do Projeto'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='observacoes_estande',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='orcamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Orçamento'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='qtd_mesas_atendimento',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de Mesas'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='referencias_dados',
            field=models.TextField(blank=True, help_text='Descreva referências de estandes anteriores ou estilos desejados', null=True, verbose_name='Referências - Dados'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='sala_reuniao_equipamentos',
            field=models.TextField(blank=True, help_text='Prateleira, TV, Armário, etc.', null=True, verbose_name='Equipamentos da Sala'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='sala_reuniao_tamanho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metragem Sala de Reunião (m²)'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='tipo_testeira',
            field=models.CharField(blank=True, choices=[('reta', 'Reta'), ('curvada', 'Curvada'), ('outro', 'Outro Estilo')], max_length=20, null=True, verbose_name='Tipo de Testeira'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='equipamentos',
            field=models.TextField(blank=True, help_text='Painel de LED, TV, etc.', null=True, verbose_name='Equipamentos'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='piso_elevado',
            field=models.CharField(blank=True, choices=[('nao', 'Sem Elevação'), ('3cm', 'Elevado 3cm'), ('10cm', 'Elevado 10cm'), ('outro', 'Outra Elevação')], max_length=20, null=True, verbose_name='Piso Elevado'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='sala_reuniao_capacidade',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Capacidade (pessoas)'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='tem_balcao_cafe',
            field=models.BooleanField(default=False, verbose_name='Balcão para Café/Bar'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='tem_balcao_recepcao',
            field=models.BooleanField(default=False, verbose_name='Balcão Recepção'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='tem_balcao_vitrine',
            field=models.BooleanField(default=False, verbose_name='Balcão Vitrine'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='tem_caixa',
            field=models.BooleanField(default=False, verbose_name='Caixa para Vendas'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='tem_copa',
            field=models.BooleanField(default=False, verbose_name='Copa'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='tem_deposito',
            field=models.BooleanField(default=False, verbose_name='Depósito'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='tem_lounge',
            field=models.BooleanField(default=False, verbose_name='Lounge'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='tem_mesas_atendimento',
            field=models.BooleanField(default=False, verbose_name='Mesas de Atendimento'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='tem_sala_reuniao',
            field=models.BooleanField(default=False, verbose_name='Sala de Reunião'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='tem_vitrine',
            field=models.BooleanField(default=False, verbose_name='Vitrine para Exposição'),
        ),
        migrations.AlterField(
            model_name='briefingvalidacao',
            name='secao',
            field=models.CharField(choices=[('evento', 'Evento - Datas e Localização'), ('estande', 'Estande - Características Físicas'), ('areas_estande', 'Áreas do Estande - Divisões Funcionais'), ('dados_complementares', 'Dados Complementares - Referências Visuais')], max_length=50),
        ),
    ]
