# Generated by Django 5.1.7 on 2025-04-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_remove_briefing_acabamentos_remove_briefing_altura_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversa',
        ),
    ]
