# Generated by Django 5.1.7 on 2025-04-21 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0010_mensagem_anexomensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='projetos/arquivos/')),
                ('nome_original', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='projetos.projeto')),
            ],
        ),
    ]
