# Generated by Django 5.1.7 on 2025-04-21 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0011_arquivoprojeto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexomensagem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='arquivoprojeto',
            options={'verbose_name': 'Arquivo do Projeto', 'verbose_name_plural': 'Arquivos do Projeto'},
        ),
        migrations.AlterModelOptions(
            name='briefing',
            options={'ordering': ['projeto', '-versao'], 'verbose_name': 'Briefing', 'verbose_name_plural': 'Briefings'},
        ),
        migrations.AlterModelOptions(
            name='briefingarquivoreferencia',
            options={'verbose_name': 'Arquivo de Referência', 'verbose_name_plural': 'Arquivos de Referência'},
        ),
        migrations.AlterModelOptions(
            name='briefingconversation',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Conversa de Briefing', 'verbose_name_plural': 'Conversas de Briefing'},
        ),
        migrations.AlterModelOptions(
            name='briefingvalidacao',
            options={'verbose_name': 'Validação de Briefing', 'verbose_name_plural': 'Validações de Briefing'},
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='briefing_status',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tem_briefing',
        ),
        migrations.AddField(
            model_name='briefing',
            name='versao',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Versão do Briefing'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='briefing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='projetos.briefing', verbose_name='Briefing'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='numero',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Sequência única por empresa', verbose_name='Número do Projeto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anexomensagem',
            name='tamanho',
            field=models.PositiveIntegerField(default=0, verbose_name='Tamanho (bytes)'),
        ),
        migrations.AlterField(
            model_name='anexomensagem',
            name='tipo_arquivo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='briefing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='etapa_atual',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Etapa Atual'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='progresso',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Progresso'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='projetos.projeto', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_validacao', 'Em Validação'), ('validado', 'Validado'), ('enviado', 'Enviado'), ('revisao', 'Em Revisão'), ('aprovado', 'Aprovado')], default='rascunho', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='validado_por_ia',
            field=models.BooleanField(default=False, verbose_name='Validado por IA'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='destacada',
            field=models.BooleanField(default=False, verbose_name='Destacada'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='lida',
            field=models.BooleanField(default=False, verbose_name='Lida'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('briefing_em_andamento', 'Briefing em Andamento'), ('briefing_validado', 'Briefing Validado'), ('briefing_enviado', 'Briefing Enviado'), ('projeto_em_desenvolvimento', 'Projeto em Desenvolvimento'), ('projeto_enviado', 'Projeto Enviado'), ('projeto_em_analise', 'Projeto em Análise'), ('projeto_aprovado', 'Projeto Aprovado'), ('em_producao', 'Em Produção'), ('concluido', 'Concluído'), ('projeto_cancelado', 'Cancelado')], default='pendente', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='briefing',
            unique_together={('projeto', 'versao')},
        ),
        migrations.AlterModelTable(
            name='arquivoprojeto',
            table='projeto_arquivos',
        ),
    ]
