# Generated by Django 5.1.7 on 2025-04-21 12:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0012_alter_anexomensagem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_aprovacao_projeto',
            field=models.DateTimeField(blank=True, help_text='Data em que o projeto foi aprovado pelo cliente', null=True, verbose_name='Data de Aprovação do Projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_entrega_estande',
            field=models.DateTimeField(blank=True, help_text='Data em que o estande foi entregue finalizado', null=True, verbose_name='Data de Entrega do Estande'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_envio_briefing',
            field=models.DateTimeField(blank=True, help_text='Data em que o último briefing foi enviado', null=True, verbose_name='Data de Envio do Briefing'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_inicio_producao',
            field=models.DateTimeField(blank=True, help_text='Data em que a produção física do estande foi iniciada', null=True, verbose_name='Data de Início da Produção'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tempo_producao',
            field=models.DurationField(blank=True, help_text='Tempo entre a aprovação do projeto e a conclusão', null=True, verbose_name='Tempo de Produção'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tempo_projeto',
            field=models.DurationField(blank=True, help_text='Tempo entre o envio do briefing e a aprovação do projeto', null=True, verbose_name='Tempo de Projeto'),
        ),
        migrations.AlterField(
            model_name='anexomensagem',
            name='tipo_arquivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProjetoMarco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('criacao_projeto', 'Criação do Projeto'), ('envio_briefing', 'Envio do Briefing'), ('validacao_briefing', 'Validação do Briefing'), ('inicio_desenvolvimento', 'Início do Desenvolvimento'), ('envio_projeto', 'Envio do Projeto'), ('analise_projeto', 'Análise do Projeto'), ('aprovacao_projeto', 'Aprovação do Projeto'), ('inicio_producao', 'Início da Produção'), ('entrega_estande', 'Entrega do Estande'), ('cancelamento', 'Cancelamento do Projeto'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de Marco')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Evento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcos', to='projetos.projeto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Marco do Projeto',
                'verbose_name_plural': 'Marcos do Projeto',
                'db_table': 'projeto_marcos',
                'ordering': ['-data'],
            },
        ),
    ]
