# Generated by Django 5.1.7 on 2025-05-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0013_projeto_data_aprovacao_projeto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('briefing_pendente', 'Briefing Pendente'), ('briefing_validado', 'Briefing Validado'), ('briefing_enviado', 'Briefing Enviado'), ('projeto_em_desenvolvimento', 'Projeto em Desenvolvimento'), ('projeto_enviado', 'Projeto Enviado'), ('projeto_em_analise', 'Projeto em Análise'), ('projeto_aprovado', 'Projeto Aprovado'), ('em_producao', 'Em Produção'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=30, verbose_name='Status'),
        ),
    ]
