# Generated by Django 5.1.7 on 2025-05-06 21:13

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0014_alter_projeto_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefing',
            name='area_aberta_tamanho',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='copa_equipamentos',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='copa_tamanho',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='cores',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='deposito_equipamentos',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='deposito_tamanho',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='equipamentos',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='havera_ativacao',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='havera_venda',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='local_evento',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='nome_projeto',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='observacoes_estande',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='qtd_mesas_atendimento',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='sala_reuniao_capacidade',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='sala_reuniao_equipamentos',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='sala_reuniao_tamanho',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='tem_balcao_cafe',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='tem_balcao_recepcao',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='tem_balcao_vitrine',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='tem_caixa',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='tem_copa',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='tem_deposito',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='tem_lounge',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='tem_mesas_atendimento',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='tem_sala_reuniao',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='tem_vitrine',
        ),
        migrations.AddField(
            model_name='briefing',
            name='mapa_estande',
            field=models.FileField(blank=True, null=True, storage=core.storage.MinioStorage(), upload_to='briefing/mapas/', verbose_name='Mapa do Estande'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='medida_frente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Medida Frente (m)'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='medida_fundo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Medida Fundo (m)'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='medida_lateral_direita',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Medida Lateral Direita (m)'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='medida_lateral_esquerda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Medida Lateral Esquerda (m)'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='objetivo_estande',
            field=models.TextField(blank=True, help_text='Lançamento da coleção, etc.', null=True, verbose_name='Objetivo do Estande'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='objetivo_evento',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivo do Evento'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='tipo_ativacao',
            field=models.CharField(blank=True, help_text='Área instagramável, Glorify, Games, etc.', max_length=255, null=True, verbose_name='Tipo de Ativação'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='tipo_venda',
            field=models.CharField(choices=[('nao', 'Não haverá venda'), ('loja', 'Loja'), ('balcao', 'Balcão'), ('ambos', 'Loja e Balcão')], default='nao', max_length=50, verbose_name='Tipo de Venda'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='area_estande',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculada automaticamente', max_digits=8, null=True, verbose_name='Área Total do Estande (m²)'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='endereco_estande',
            field=models.CharField(blank=True, help_text='Localização do estande dentro do pavilhão', max_length=255, null=True, verbose_name='Endereço do Estande'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='estilo_estande',
            field=models.TextField(blank=True, help_text='Ex: Moderno, Clean, Futurista, Rústico, etc.', null=True, verbose_name='Estilo do Estande'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='material',
            field=models.CharField(blank=True, choices=[('customizado', 'Customizado'), ('misto', 'Misto'), ('padrao', 'Padrão (alumínio, vidro)')], max_length=20, null=True, verbose_name='Materiais'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='piso_elevado',
            field=models.CharField(blank=True, choices=[('sem_elevacao', 'Sem Elevação'), ('3cm', 'Elevado 3cm'), ('10cm', 'Elevado 10cm'), ('outro', 'Outra Elevação')], max_length=20, null=True, verbose_name='Piso Elevado'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='tipo_testeira',
            field=models.CharField(blank=True, choices=[('reta', 'Reta'), ('curva', 'Curva'), ('outro', 'Outro')], max_length=20, null=True, verbose_name='Tipo Testeira'),
        ),
        migrations.CreateModel(
            name='AreaExposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_lounge', models.BooleanField(default=False, verbose_name='Lounge')),
                ('tem_vitrine_exposicao', models.BooleanField(default=False, verbose_name='Vitrine Exposição')),
                ('tem_balcao_recepcao', models.BooleanField(default=False, verbose_name='Balcão Recepção')),
                ('tem_mesas_atendimento', models.BooleanField(default=False, verbose_name='Mesas de Atendimento')),
                ('tem_balcao_cafe', models.BooleanField(default=False, verbose_name='Balcão para Café/Bar')),
                ('tem_balcao_vitrine', models.BooleanField(default=False, verbose_name='Balcão Vitrine')),
                ('tem_caixa_vendas', models.BooleanField(default=False, verbose_name='Caixa para Vendas')),
                ('equipamentos', models.TextField(blank=True, help_text='LED, TVs, etc.', null=True, verbose_name='Equipamentos')),
                ('observacoes', models.TextField(blank=True, help_text='Coloque aqui como você imagina a área de exposição', null=True, verbose_name='Observações')),
                ('metragem', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metragem (m²)')),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_exposicao', to='projetos.briefing')),
            ],
            options={
                'verbose_name': 'Área de Exposição',
                'verbose_name_plural': 'Áreas de Exposição',
            },
        ),
        migrations.CreateModel(
            name='Copa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamentos', models.TextField(blank=True, help_text='Pia, geladeira, bancada, prateleiras, etc.', null=True, verbose_name='Equipamentos')),
                ('metragem', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metragem (m²)')),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copas', to='projetos.briefing')),
            ],
            options={
                'verbose_name': 'Copa',
                'verbose_name_plural': 'Copas',
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamentos', models.TextField(blank=True, help_text='Prateleiras, etc.', null=True, verbose_name='Equipamentos')),
                ('metragem', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metragem (m²)')),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='projetos.briefing')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
            },
        ),
        migrations.CreateModel(
            name='SalaReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade', models.PositiveSmallIntegerField(default=0, verbose_name='Capacidade (pessoas)')),
                ('equipamentos', models.TextField(blank=True, help_text='Prateleira, TV, armário, estilo mesa, etc.', null=True, verbose_name='Equipamentos')),
                ('metragem', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metragem (m²)')),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_reuniao', to='projetos.briefing')),
            ],
            options={
                'verbose_name': 'Sala de Reunião',
                'verbose_name_plural': 'Salas de Reunião',
            },
        ),
    ]
