# Generated by Django 5.1.7 on 2025-05-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0015_remove_briefing_area_aberta_tamanho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefing',
            name='data_desmontagem_fim',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='data_desmontagem_inicio',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='data_feira_fim',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='data_feira_inicio',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='data_montagem_fim',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='data_montagem_inicio',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='horario_feira',
        ),
    ]
