# Generated by Django 5.1.7 on 2025-05-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0016_remove_briefing_data_desmontagem_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='briefings/'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='briefingvalidacao',
            name='secao',
            field=models.CharField(choices=[('evento', 'Local Estande'), ('estande', 'Características'), ('areas_estande', 'Divisões'), ('dados_complementares', 'Referências Visuais')], max_length=50),
        ),
    ]
