# Generated by Django 5.1.7 on 2025-05-13 20:02

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0018_auto_20250513_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tipo_projeto',
            field=models.CharField(choices=[('feira', 'Feira de Negócios'), ('outros', 'Outros')], default='feira', max_length=20, verbose_name='Tipo de Projeto'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=core.storage.MinioStorage(), upload_to='briefings/', verbose_name='Arquivo PDF do Relatório'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Geração do PDF'),
        ),
        migrations.CreateModel(
            name='ProjetoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Planta')),
                ('arquivo', models.FileField(storage=core.storage.MinioStorage(), upload_to='projetos/plantas/', verbose_name='Arquivo da Planta')),
                ('tipo', models.CharField(choices=[('localizacao', 'Planta de Localização'), ('estande', 'Planta do Estande'), ('pavilhao', 'Planta do Pavilhão'), ('outro', 'Outro Tipo')], max_length=50, verbose_name='Tipo de Planta')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Planta do Projeto',
                'verbose_name_plural': 'Plantas do Projeto',
                'db_table': 'projeto_plantas',
            },
        ),
        migrations.CreateModel(
            name='ProjetoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Referência')),
                ('arquivo', models.FileField(storage=core.storage.MinioStorage(), upload_to='projetos/referencias/', verbose_name='Arquivo de Referência')),
                ('tipo', models.CharField(choices=[('estande_anterior', 'Estande Anterior'), ('estilo_visual', 'Estilo Visual'), ('logotipo', 'Logotipo'), ('campanha', 'Material de Campanha'), ('imagem', 'Imagem de Referência'), ('documento', 'Documento'), ('outro', 'Outro')], max_length=50, verbose_name='Tipo de Referência')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Referência do Projeto',
                'verbose_name_plural': 'Referências do Projeto',
                'db_table': 'projeto_referencias',
            },
        ),
    ]
