# Generated by Django 5.1.7 on 2025-05-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0019_projeto_tipo_projeto_alter_briefing_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing',
            name='tipo_stand',
            field=models.CharField(blank=True, choices=[('ilha', 'Ilha'), ('ponta_ilha', 'Ponta de Ilha'), ('esquina', 'Esquina'), ('corredor', 'Corredor'), ('box', 'Box')], max_length=20, null=True, verbose_name='Tipo de Stand'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('aguardando_manual', 'Aguardando Manual'), ('briefing_pendente', 'Briefing Pendente'), ('briefing_validado', 'Briefing Validado'), ('briefing_enviado', 'Briefing Enviado'), ('projeto_em_desenvolvimento', 'Projeto em Desenvolvimento'), ('projeto_enviado', 'Projeto Enviado'), ('projeto_em_analise', 'Projeto em Análise'), ('projeto_aprovado', 'Projeto Aprovado'), ('em_producao', 'Em Produção'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo_projeto',
            field=models.CharField(choices=[('feira_negocios', 'Feira de Negócios'), ('outros', 'Outros')], default='feira_negocios', max_length=20, verbose_name='Tipo de Projeto'),
        ),
    ]
