# Generated by Django 5.1.7 on 2025-05-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0020_briefing_tipo_stand_alter_projeto_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefing',
            name='mapa_estande',
        ),
        migrations.AddField(
            model_name='briefing',
            name='dimensoes_projeto',
            field=models.TextField(blank=True, null=True, verbose_name='Dimensões do Projeto'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='evento_cidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade/Estado'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='evento_data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='evento_data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='evento_horario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='evento_local',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local do Evento'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='evento_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Evento'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='evento_organizador',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organizador'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='observacoes_cronograma',
            field=models.TextField(blank=True, null=True, verbose_name='Observações sobre o Cronograma'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='periodo_desmontagem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Período de Desmontagem'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='periodo_montagem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Período de Montagem'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='tipo_projeto_outros',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Projeto'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='material',
            field=models.CharField(blank=True, choices=[('construido', 'Construido'), ('misto', 'Misto'), ('padrao', 'Padrão (alumínio, vidro)')], max_length=20, null=True, verbose_name='Materiais'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='tipo_stand',
            field=models.CharField(choices=[('ilha', 'Ilha'), ('ponta_ilha', 'Ponta de Ilha'), ('esquina', 'Esquina'), ('corredor', 'Corredor'), ('box', 'Box')], default='esquina', max_length=20, verbose_name='Tipo de Stand'),
        ),
        migrations.AlterField(
            model_name='briefingarquivoreferencia',
            name='tipo',
            field=models.CharField(choices=[('mapa', 'Mapa do Estande'), ('planta', 'Planta/Esboço'), ('referencia', 'Referência'), ('campanha', 'Material de Campanha'), ('outro', 'Outro Material')], max_length=50),
        ),
    ]
