# Generated by Django 5.1.7 on 2025-05-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0021_remove_briefing_mapa_estande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefing',
            name='dimensoes_projeto',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='evento_cidade',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='evento_data_fim',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='evento_data_inicio',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='evento_horario',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='evento_local',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='evento_nome',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='evento_organizador',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='observacoes_cronograma',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='periodo_desmontagem',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='periodo_montagem',
        ),
        migrations.RemoveField(
            model_name='briefing',
            name='tipo_projeto_outros',
        ),
        migrations.AddField(
            model_name='briefing',
            name='data_horario_evento',
            field=models.CharField(blank=True, help_text='Período e horário de funcionamento do evento', max_length=255, null=True, verbose_name='Data e Horário'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='local_evento',
            field=models.CharField(blank=True, help_text='Local completo onde o evento será realizado (incluindo cidade/estado)', max_length=255, null=True, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='nome_evento',
            field=models.CharField(blank=True, help_text='Nome do evento ou feira', max_length=255, null=True, verbose_name='Nome do Evento'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='organizador_evento',
            field=models.CharField(blank=True, help_text='Empresa ou pessoa responsável pela organização do evento', max_length=255, null=True, verbose_name='Organizador'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='periodo_desmontagem_evento',
            field=models.CharField(blank=True, help_text='Datas e horários para desmontagem', max_length=255, null=True, verbose_name='Período de Desmontagem'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='periodo_montagem_evento',
            field=models.CharField(blank=True, help_text='Datas e horários disponíveis para montagem', max_length=255, null=True, verbose_name='Período de Montagem'),
        ),
    ]
