# Generated by Django 5.1.7 on 2025-05-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0023_projeto_projetista'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='status_desenvolvimento',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('conceito_visual', 'Conceito Visual'), ('renderizacao_3d', 'Renderização 3D'), ('projeto_executivo', 'Projeto Executivo'), ('calculo_custos', 'Cálculo de Custos'), ('detalhamento', 'Detalhamento'), ('concluido', 'Concluído')], default='nao_iniciado', max_length=30, verbose_name='Status de Desenvolvimento'),
        ),
    ]
