# Generated by Django 5.1.7 on 2025-06-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0024_projeto_status_desenvolvimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefing',
            name='piso_elevado',
            field=models.CharField(blank=True, choices=[('sem_elevacao', 'Sem Elevação'), ('3cm', 'Elevado 3cm'), ('10cm', 'Elevado 10cm'), ('livre', 'A ser definida')], max_length=20, null=True, verbose_name='Piso Elevado'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='tipo_testeira',
            field=models.CharField(blank=True, choices=[('reta', 'Reta'), ('curva', 'Curva'), ('livre', 'A ser definida')], max_length=20, null=True, verbose_name='Tipo Testeira'),
        ),
    ]
