# Generated by Django 5.1.7 on 2025-07-27 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0025_alter_briefing_piso_elevado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_elevacao_podium', models.BooleanField(default=False, verbose_name='Elevação/Pódium')),
                ('tem_sistema_som', models.BooleanField(default=False, verbose_name='Sistema de Som')),
                ('tem_microfone', models.BooleanField(default=False, verbose_name='Microfone')),
                ('tem_telao_tv', models.BooleanField(default=False, verbose_name='Telão/TV')),
                ('tem_iluminacao_cenica', models.BooleanField(default=False, verbose_name='Iluminação Cênica')),
                ('tem_backdrop_cenario', models.BooleanField(default=False, verbose_name='Backdrop/Cenário')),
                ('tem_bancada_demonstracao', models.BooleanField(default=False, verbose_name='Bancada Demonstração')),
                ('tem_espaco_plateia', models.BooleanField(default=False, verbose_name='Espaço Plateia')),
                ('equipamentos', models.TextField(blank=True, help_text='Detalhes adicionais sobre equipamentos específicos', null=True, verbose_name='Equipamentos')),
                ('observacoes', models.TextField(blank=True, help_text='Coloque aqui como você imagina o palco', null=True, verbose_name='Observações')),
                ('metragem', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metragem (m²)')),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palcos', to='projetos.briefing')),
            ],
            options={
                'verbose_name': 'Palco',
                'verbose_name_plural': 'Palcos',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_bancada_trabalho', models.BooleanField(default=False, verbose_name='Bancada de Trabalho')),
                ('tem_mesas_participantes', models.BooleanField(default=False, verbose_name='Mesas Participantes')),
                ('tem_cadeiras_bancos', models.BooleanField(default=False, verbose_name='Cadeiras/Bancos')),
                ('tem_quadro_flipchart', models.BooleanField(default=False, verbose_name='Quadro/Flipchart')),
                ('tem_projetor_tv', models.BooleanField(default=False, verbose_name='Projetor/TV')),
                ('tem_pia_bancada_molhada', models.BooleanField(default=False, verbose_name='Pia/Bancada Molhada')),
                ('tem_armario_materiais', models.BooleanField(default=False, verbose_name='Armário Materiais')),
                ('tem_pontos_eletricos_extras', models.BooleanField(default=False, verbose_name='Pontos Elétricos Extras')),
                ('equipamentos', models.TextField(blank=True, help_text='Detalhes adicionais sobre equipamentos específicos', null=True, verbose_name='Equipamentos')),
                ('observacoes', models.TextField(blank=True, help_text='Coloque aqui como você imagina o workshop', null=True, verbose_name='Observações')),
                ('metragem', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metragem (m²)')),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='projetos.briefing')),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
            },
        ),
    ]
