# Generated by Django 5.1.7 on 2025-07-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0026_palco_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='salareuniao',
            name='tipo_sala',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='fechada', max_length=10, verbose_name='Tipo de Sala'),
        ),
    ]
