# Generated by Django 5.1.7 on 2025-08-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0027_salareuniao_tipo_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='analise_visual_processada',
            field=models.BooleanField(default=False, verbose_name='Análise Visual Processada'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_analise_visual',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Análise Visual'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='inspiracoes_visuais',
            field=models.JSONField(blank=True, default=dict, help_text='Análise das imagens de referência enviadas pelo cliente', verbose_name='Inspirações das Referências'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='layout_identificado',
            field=models.JSONField(blank=True, default=dict, help_text='Estrutura JSON com áreas identificadas no esboço da planta', verbose_name='Layout do Esboço Identificado'),
        ),
    ]
