# Generated by Django 5.1.7 on 2025-09-21 17:09

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0028_projeto_analise_visual_processada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceitoVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_usado', models.TextField(help_text='Prompt completo usado para gerar a imagem', verbose_name='Prompt Utilizado')),
                ('prompt_customizado', models.BooleanField(default=False, help_text='Se o usuário editou o prompt antes de gerar', verbose_name='Prompt foi customizado')),
                ('layout_usado', models.JSONField(default=dict, help_text='Dados do layout (Etapa 1) usados na geração', verbose_name='Layout do Esboço')),
                ('inspiracoes_usadas', models.JSONField(default=dict, help_text='Dados das inspirações (Etapa 2) usadas na geração', verbose_name='Inspirações Visuais')),
                ('dataset_consolidado', models.JSONField(blank=True, default=dict, help_text='Dados consolidados para debug', verbose_name='Dataset Consolidado')),
                ('image_url_original', models.URLField(blank=True, help_text='URL retornada pelo serviço de geração', max_length=500, null=True, verbose_name='URL Original da Imagem')),
                ('imagem', models.ImageField(blank=True, help_text='Cópia local da imagem gerada', null=True, storage=core.storage.MinioStorage(), upload_to='conceitos_visuais/', verbose_name='Imagem Local')),
                ('modelo_ia', models.CharField(choices=[('dall-e-3', 'DALL-E 3'), ('dall-e-2', 'DALL-E 2'), ('midjourney', 'Midjourney'), ('stable-diffusion', 'Stable Diffusion'), ('stub', 'Imagem de Teste')], default='dall-e-3', max_length=50, verbose_name='Modelo de IA Usado')),
                ('metricas_geracao', models.JSONField(blank=True, default=dict, help_text='Tamanho do prompt, resolução, tempo, etc.', verbose_name='Métricas da Geração')),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro'), ('aprovado', 'Aprovado pelo Cliente'), ('rejeitado', 'Rejeitado pelo Cliente')], default='processando', max_length=20, verbose_name='Status')),
                ('erro_detalhes', models.TextField(blank=True, help_text='Se houve erro na geração', null=True, verbose_name='Detalhes do Erro')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('comentarios_cliente', models.TextField(blank=True, null=True, verbose_name='Comentários do Cliente')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão do Conceito')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceitos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceitos_visuais', to='projetos.briefing')),
                ('conceito_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes_posteriores', to='projetos.conceitovisual')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceitos_visuais', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Conceito Visual',
                'verbose_name_plural': 'Conceitos Visuais',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['projeto', '-versao'], name='projetos_co_projeto_c6aae1_idx'), models.Index(fields=['status', 'criado_em'], name='projetos_co_status_ac2801_idx')],
            },
        ),
    ]
