# Generated by Django 5.1.7 on 2025-11-09 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_crewtask_output_file'),
        ('projetos', '0029_conceitovisual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='briefing',
            index=models.Index(fields=['projeto', '-updated_at'], name='idx_brief_proj_updated'),
        ),
        migrations.AddIndex(
            model_name='briefing',
            index=models.Index(fields=['status'], name='idx_brief_status'),
        ),
        migrations.AddIndex(
            model_name='briefing',
            index=models.Index(fields=['etapa_atual'], name='idx_brief_etapa'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['empresa', '-created_at'], name='idx_proj_emp_created'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['status'], name='idx_proj_status'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['feira'], name='idx_proj_feira'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['tipo_projeto'], name='idx_proj_tipo'),
        ),
        migrations.AlterModelTable(
            name='briefing',
            table='briefings',
        ),
    ]
