# Generated by Django 5.1.7 on 2025-11-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0030_briefing_idx_brief_proj_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_planta_baixa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Geração da Planta Baixa'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='planta_baixa_json',
            field=models.JSONField(blank=True, default=dict, help_text='Dados estruturados da planta baixa (layout, áreas, dimensões)', verbose_name='Planta Baixa Estruturada'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='planta_baixa_processada',
            field=models.BooleanField(default=False, verbose_name='Planta Baixa Processada'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='planta_baixa_svg',
            field=models.TextField(blank=True, help_text='Desenho técnico em formato SVG para visualização', null=True, verbose_name='Representação SVG da Planta'),
        ),
    ]
