# Generated by Django 5.1.7 on 2025-11-09 22:50

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0031_projeto_data_planta_baixa_projeto_planta_baixa_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='arquivo_3d',
            field=models.FileField(blank=True, help_text='Modelo 3D exportado (.skp)', null=True, storage=core.storage.MinioStorage(), upload_to='modelos_3d/', verbose_name='Arquivo 3D (SketchUp)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_modelo_3d',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Geração do Modelo 3D'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_renderizacao_ai',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Renderização AI'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem_conceito_url',
            field=models.URLField(blank=True, help_text='Link da imagem conceitual gerada pela IA', max_length=500, null=True, verbose_name='URL da Imagem DALL-E'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='modelo_3d_processado',
            field=models.BooleanField(default=False, verbose_name='Modelo 3D Processado'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='prompt_dalle_atual',
            field=models.TextField(blank=True, help_text='Último prompt usado para gerar a imagem', null=True, verbose_name='Prompt DALL-E Atual'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='renderizacao_ai_json',
            field=models.JSONField(blank=True, default=dict, help_text='JSON enriquecido com planta + briefing + elementos visuais', verbose_name='Conceito Visual Enriquecido'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='renderizacao_ai_processada',
            field=models.BooleanField(default=False, verbose_name='Renderização AI Processada'),
        ),
    ]
