# Generated by Django 5.1.7 on 2025-05-17 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0023_projeto_projetista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceitoVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do Conceito')),
                ('referencias_utilizadas', models.TextField(blank=True, verbose_name='Referências Utilizadas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('briefing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conceito_visual', to='projetos.briefing')),
                ('projetista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceitos_criados', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceitos_visuais', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Conceito Visual',
                'verbose_name_plural': 'Conceitos Visuais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemConceitoVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='conceitos_visuais/%Y/%m/%d/')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('conceito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='projetista.conceitovisual')),
            ],
            options={
                'verbose_name': 'Imagem do Conceito',
                'verbose_name_plural': 'Imagens do Conceito',
                'ordering': ['ordem'],
            },
        ),
    ]
