# Generated by Django 5.1.7 on 2025-05-18 15:24

import core.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_feira_materiais_remove_feira_outros_and_more'),
        ('projetista', '0001_initial'),
        ('projetos', '0024_projeto_status_desenvolvimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemconceitovisual',
            options={'ordering': ['ordem', 'criado_em'], 'verbose_name': 'Imagem de Conceito', 'verbose_name_plural': 'Imagens de Conceito'},
        ),
        migrations.RemoveField(
            model_name='conceitovisual',
            name='referencias_utilizadas',
        ),
        migrations.AddField(
            model_name='conceitovisual',
            name='agente_usado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceitos_gerados', to='core.agente', verbose_name='Agente Utilizado'),
        ),
        migrations.AddField(
            model_name='conceitovisual',
            name='ia_gerado',
            field=models.BooleanField(default=False, verbose_name='Gerado por IA'),
        ),
        migrations.AddField(
            model_name='conceitovisual',
            name='materiais_principais',
            field=models.TextField(blank=True, null=True, verbose_name='Materiais Principais'),
        ),
        migrations.AddField(
            model_name='conceitovisual',
            name='paleta_cores',
            field=models.TextField(blank=True, null=True, verbose_name='Paleta de Cores'),
        ),
        migrations.AddField(
            model_name='conceitovisual',
            name='status',
            field=models.CharField(choices=[('em_elaboracao', 'Em Elaboração'), ('aguardando_imagens', 'Aguardando Imagens'), ('finalizado', 'Finalizado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='em_elaboracao', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='conceitovisual',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título do Conceito'),
        ),
        migrations.AddField(
            model_name='imagemconceitovisual',
            name='angulo_vista',
            field=models.CharField(choices=[('frontal', 'Vista Frontal'), ('perspectiva', 'Perspectiva Externa'), ('lateral_esquerda', 'Lateral Esquerda'), ('lateral_direita', 'Lateral Direita'), ('interior', 'Vista Interior'), ('superior', 'Vista Superior/Planta'), ('detalhe', 'Detalhe'), ('outro', 'Outro Ângulo')], default='outro', max_length=50, verbose_name='Ângulo/Vista'),
        ),
        migrations.AddField(
            model_name='imagemconceitovisual',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemconceitovisual',
            name='ia_gerada',
            field=models.BooleanField(default=False, verbose_name='Gerada por IA'),
        ),
        migrations.AlterField(
            model_name='conceitovisual',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='conceitovisual',
            name='briefing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceitos_visuais', to='projetos.briefing'),
        ),
        migrations.AlterField(
            model_name='conceitovisual',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='conceitovisual',
            name='projetista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceitos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagemconceitovisual',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='imagemconceitovisual',
            name='imagem',
            field=models.ImageField(storage=core.storage.MinioStorage(), upload_to='conceitos_visuais/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='imagemconceitovisual',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
    ]
