# Generated by Django 5.1.7 on 2025-05-19 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetista', '0002_alter_imagemconceitovisual_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceitovisual',
            name='elementos_interativos',
            field=models.TextField(blank=True, help_text='Descrição de como os visitantes interagirão com o espaço', null=True, verbose_name='Elementos Interativos'),
        ),
        migrations.AddField(
            model_name='conceitovisual',
            name='etapa_atual',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Conceito Textual'), (2, 'Imagem Principal'), (3, 'Múltiplas Vistas'), (4, 'Concluído')], default=1, verbose_name='Etapa Atual'),
        ),
        migrations.AddField(
            model_name='conceitovisual',
            name='imagem_principal_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Imagem Principal'),
        ),
        migrations.AddField(
            model_name='conceitovisual',
            name='imagem_principal_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='Prompt para Imagem Principal'),
        ),
        migrations.AddField(
            model_name='imagemconceitovisual',
            name='imagem_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes_posteriores', to='projetista.imagemconceitovisual', verbose_name='Versão Anterior'),
        ),
        migrations.AddField(
            model_name='imagemconceitovisual',
            name='principal',
            field=models.BooleanField(default=False, verbose_name='Imagem Principal'),
        ),
        migrations.AddField(
            model_name='imagemconceitovisual',
            name='prompt_geracao',
            field=models.TextField(blank=True, null=True, verbose_name='Prompt de Geração'),
        ),
        migrations.AddField(
            model_name='imagemconceitovisual',
            name='versao',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Versão'),
        ),
    ]
