# Generated by Django 5.1.7 on 2025-06-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetista', '0003_conceitovisual_elementos_interativos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageVistasPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Pacote')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('vistas_incluidas', models.JSONField(help_text='Lista dos angulos_vista incluídos neste pacote', verbose_name='Vistas Incluídas')),
                ('tipo', models.CharField(choices=[('cliente', 'Apresentação Cliente'), ('tecnico', 'Técnico Completo'), ('fotogrametria', 'Fotogrametria'), ('basico', 'Básico')], max_length=20, verbose_name='Tipo do Pacote')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pacote de Vistas',
                'verbose_name_plural': 'Pacotes de Vistas',
                'ordering': ['tipo', 'ordem'],
            },
        ),
        migrations.AlterModelOptions(
            name='imagemconceitovisual',
            options={'ordering': ['categoria', 'ordem', 'criado_em'], 'verbose_name': 'Imagem de Conceito', 'verbose_name_plural': 'Imagens de Conceito'},
        ),
        migrations.AddField(
            model_name='imagemconceitovisual',
            name='categoria',
            field=models.CharField(choices=[('cliente', 'Apresentação para Cliente'), ('tecnica_externa', 'Técnica Externa'), ('tecnica_interna', 'Técnica Interna'), ('planta_elevacao', 'Plantas e Elevações'), ('detalhes', 'Detalhes Específicos')], default='cliente', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='imagemconceitovisual',
            name='coordenada_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Coordenada X (opcional)'),
        ),
        migrations.AddField(
            model_name='imagemconceitovisual',
            name='coordenada_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Coordenada Y (opcional)'),
        ),
        migrations.AddField(
            model_name='imagemconceitovisual',
            name='coordenada_z',
            field=models.FloatField(blank=True, null=True, verbose_name='Coordenada Z (opcional)'),
        ),
        migrations.AddField(
            model_name='imagemconceitovisual',
            name='essencial_fotogrametria',
            field=models.BooleanField(default=False, verbose_name='Essencial para Fotogrametria'),
        ),
        migrations.AlterField(
            model_name='imagemconceitovisual',
            name='angulo_vista',
            field=models.CharField(choices=[('perspectiva_externa', 'Perspectiva Externa Principal'), ('entrada_recepcao', 'Vista da Entrada/Recepção'), ('interior_principal', 'Vista Interna Principal'), ('area_produtos', 'Área de Produtos/Destaque'), ('elevacao_frontal', 'Elevação Frontal'), ('elevacao_lateral_esquerda', 'Elevação Lateral Esquerda'), ('elevacao_lateral_direita', 'Elevação Lateral Direita'), ('elevacao_fundos', 'Elevação Fundos'), ('quina_frontal_esquerda', 'Quina Frontal-Esquerda'), ('quina_frontal_direita', 'Quina Frontal-Direita'), ('planta_baixa', 'Planta Baixa'), ('vista_superior', 'Vista Superior'), ('interior_parede_norte', 'Interior - Parede Norte'), ('interior_parede_sul', 'Interior - Parede Sul'), ('interior_parede_leste', 'Interior - Parede Leste'), ('interior_parede_oeste', 'Interior - Parede Oeste'), ('interior_perspectiva_1', 'Interior - Perspectiva 1'), ('interior_perspectiva_2', 'Interior - Perspectiva 2'), ('interior_perspectiva_3', 'Interior - Perspectiva 3'), ('detalhe_balcao', 'Detalhe do Balcão'), ('detalhe_display', 'Detalhe dos Displays'), ('detalhe_iluminacao', 'Detalhe da Iluminação'), ('detalhe_entrada', 'Detalhe da Entrada'), ('outro', 'Outro Ângulo')], default='outro', max_length=50, verbose_name='Ângulo/Vista'),
        ),
    ]
